# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[6, 1, 0, 3, 4, 7, 6, 8, 1, 4, 4, 4],
       [3, 9, 3, 4, 9, 0, 8, 1, 0, 3, 8, 9],
       [7, 5, 9, 1, 3, 5, 3, 1, 7, 7, 5, 1],
       [8, 6, 3, 4, 7, 8, 9, 2, 3, 3, 4, 9],
       [5, 2, 6, 6, 8, 0, 6, 0, 5, 7, 9, 3],
       [0, 5, 9, 9, 4, 3, 3, 4, 3, 7, 2, 7],
       [4, 1, 4, 2, 6, 5, 6, 0, 3, 0, 2, 0],
       [6, 5, 8, 7, 3, 8, 0, 3, 8, 6, 3, 3],
       [6, 1, 6, 5, 1, 4, 0, 7, 2, 5, 1, 8],
       [2, 4, 6, 8, 2, 0, 6, 2, 8, 9, 2, 5],
       [3, 4, 6, 0, 4, 7, 5, 2, 4, 4, 3, 7],
       [1, 7, 5, 9, 4, 5, 9, 7, 1, 0, 5, 6]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

C:\Users\Kim_yoonji\AppData\Local\Temp\ipykernel_21076\2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[6, 1, 0, 3, 4, 7, 6, 8, 1, 4, 4, 4],
       [3, 9, 3, 4, 9, 0, 8, 1, 0, 3, 8, 9],
       [7, 5, 9, 1, 3, 5, 3, 1, 7, 7, 5, 1],
       [8, 6, 3, 4, 7, 8, 9, 2, 3, 3, 4, 9],
       [5, 2, 6, 6, 8, 0, 6, 0, 5, 7, 9, 3],
       [0, 5, 9, 9, 4, 3, 3, 4, 3, 7, 2, 7],
       [4, 1, 4, 2, 6, 5, 6, 0, 3, 0, 2, 0],
       [6, 5, 8, 7, 3, 8, 0, 3, 8, 6, 3, 3],
       [6, 1, 6, 5, 1, 4, 0, 7, 2, 5, 1, 8],
       [2, 4, 6, 8, 2, 0, 6, 2, 8, 9, 2, 5],
       [3, 4, 6, 0, 4, 7, 5, 2, 4, 4, 3, 7],
       [1, 7, 5, 9, 4, 5, 9, 7, 1, 0, 5, 6]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  24, -10,   0,  25, -29,  22, -13, -12,  -7,  11,   0],
       [  0, -11,  24, -16, -10,   6, -11,  -9,  17,  10,   0,   0],
       [  0,   6, -13,  -1,   5,  11,  17,  -5,  -5,  -9, -10,   0],
       [  0, -14,   4,  -3,  15, -25,  12, -17,   7,   4,  20,   0],
       [  0,   8,  12,  15, -10,   0,  -7,  10,  -7,  16, -17,   0],
       [  0, -14,  -4, -18,  10,  -3,  16, -16,   1, -18,   3,   0],
       [  0,   4,  10,  10, -10,  20, -17,  -3,  18,   8,   0,   0],
       [  0, -17,   4,  -2, -10,   7, -17,  21, -20,   2, -14,   0],
       [  0,   3,   0,  19,  -5, -19,  17, -15,  15,  17, -10,   0],
       [  0,  -4,   9, -27,   3,  14,  -4, -10,   1,   0,  -6,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [17]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()